### ISSUE TITLE
Doesn't work with bel server-side - no require('bel').createElement

### ISSUE THREAD

**Issue by nilliams** [aaaristo/rbel#1]
I found this doesn't work with `bel` for SSR, e.g. if using choo's `.toString()` because `require('bel').createElement` doesn't exist on the server.

(`bel` uses the `pelo` module on the server, which does not export a `createElement`).

Not sure if there's a sensible workaround, but worth adding a note to the readme?

**Comment by JRJurman** [comment]
This is an issue with bel, not with rbel. You can post it on their repo, however, if you just want the create-element function, you can try this: https://github.com/jrjurman/bel-create-element

**Comment by nilliams** [comment]
Cool, thank you for the link to bel-create-element, I will try that out when I get a chance!

Yes I appreciate the inconsistency in the bel API is not the fault of this module, I was just suggesting a warning in the readme.

No big deal though, just wanted to raise as I burned a bit of time figuring out what was going on. Feel free to close!

**Comment by aaaristo** [comment]
Added to the readme. Thanks.
